name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Set working directory
        run: cd dreamsquad-ff-backend  

      - name: Run tests
        run: |
          pytest tests/  # Specify the tests directory

      - name: Deploy to Render
        if: github.event_name == 'push'
        run: |
          curl -X POST https://api.render.com/deploy/${{ secrets.RENDER_WEB_SERVICE_ID }} \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_TOKEN }}"